# Generated by Django 4.2.6 on 2023-12-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='base.branch'),
        ),
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='base.repository'),
        ),
    ]
