# Generated by Django 4.2.6 on 2023-12-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_file_file_file_branch_file_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='file',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.repository'),
        ),
    ]
